# Generated by Django 5.0.4 on 2024-04-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_post_comment_delete_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
